TARGET := test
test: main.cpp action.hpp graph.hpp dfs.hpp bfs.hpp disjointed_set.hpp mst.hpp kruskal.hpp edge.hpp prim.hpp kosaraju.hpp
	g++ -g  -O0  $^   -std=c++11 -std=gnu++11  -gdwarf-2  -o $(TARGET)
all: test


